### ISSUE TITLE
Pre-trained model links are broken

### ISSUE THREAD

**Issue by ofirkris** [zhmiao/OpenCompoundDomainAdaptation-OCDA#1]
Hi, thanks for sharing this project - can you kindly update the links to the pre-trained models?

**Comment by zhmiao** [comment]
Hello @ofirkris , thanks for asking! We are currently working on releasing the pretrained models. We will notify you as soon as the link is valid. Thanks again! For now I will temporarily close this issue if you are fine with that.

**Comment by zhmiao** [comment]
Hello @ofirkris , we have updated link for pretrained C-digits model. Please check out the updated readme. Thank you very much!
